# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ExploGitApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Kingfisher'
  pod 'KeychainSwift'
  pod 'SwiftGen'	

  # networking
  pod 'Alamofire', '4.7.3'
  pod 'Moya/RxSwift', '13.0.1'
  pod 'PromiseKit', '6.10.0'

end
